Preview mode
tinacms/tina-cloud-starter pull request #59
Opened 2021-04-30 16:58 UTC by jeffsee55

2021-04-30 17:01 UTC, jeffsee55 commented on pages/posts/[filename].tsx
> +    },
This shape is required for _all_ `getStaticProps` return values. Perhaps we could be a helper function or typescript type

2021-04-30 17:01 UTC, jeffsee55 commented on pages/api/preview.js
> +  res.redirect("/");
@logan-anderson says there's a clean way to grab the referrer URL and send the user back to it 👍

2021-04-30 18:04 UTC, logan-anderson commented
@jeffsee55  I was able to remove nextjs preview mode from this implementation see https://github.com/tinacms/tina-cloud-starter/pull/60

2021-04-30 18:25 UTC, jeffsee55 commented
Closing in favor of https://github.com/tinacms/tina-cloud-starter/pull/60. Not sure we'll merge any of this just yet regardless, the "admin" pattern seems to put people's minds at ease that they won't be loading Tina in production views so even though this still works we should get some feedback from others

2021-05-03 15:45 UTC, jeffsee55 commented
Merged in Logan's changes, much better since we weren't really using preview mode for it's actual purpose.

2021-05-11 12:48 UTC, logan-anderson commented
Issue here https://github.com/tinacms/tina-cloud-starter/issues/63

@jeffsee55 @DirtyF  @dwalkr @Enigmatical I updated the Readme and added some comments in the code wouldn’t mind a second set of eyes.

2021-05-11 14:23 UTC, DirtyF commented on pages/_app.js
> +    // Dynamically load tina ONLY when in edit mode so it does not effect the bundle
```suggestion
    // Dynamically load Tina only when in edit mode so it does not affect production
```

2021-05-11 14:24 UTC, DirtyF commented on pages/_app.js
> +// Return the app wrapped in the edit provider
```suggestion
// Our app is wrapped with edit provider
```

2021-05-11 15:16 UTC, Enigmatical commented
Got a handful of conflicts on here (nothing serious, I suspect).  Once those are resolved, I'm happy to take a look at the finished PR 👍

2021-05-11 15:26 UTC, logan-anderson commented
> Got a handful of conflicts on here (nothing serious, I suspect). Once those are resolved, I'm happy to take a look at the finished PR 👍

@Enigmatical  Should be good now

2021-05-11 18:42 UTC, Enigmatical requested changes
I left some comments that can be pretty quickly addressed.  I have a bigger one, but I'll bring that up in the #oss channel.

2021-05-11 18:42 UTC, Enigmatical commented on components/Spinner/index.tsx
> +  text = "Wait a bit, Tina is loading data from GitHub",
I'm assuming this shows when you are working locally, as well?  Do we just want to truncate the "from GitHub" to make it agnostic?

"Wait a bit, Tina is loading data"

2021-05-11 18:42 UTC, Enigmatical commented on utils/editState.tsx
> +const LOCALSTORAGEKEY = 'tinaisadmin'
Not a blocker, but we might want to better namespace this?  `tinacms.isEditing` or `tina.isEditing`?  I doubt we're going to brush up against existing keys and I don't know how much LOCALSTORAGE is used elsewhere.

2021-05-11 18:42 UTC, Enigmatical commented on utils/editState.tsx
> +        console.log(isEditing?  'true': 'false')
Probably safe to remove these.

2021-05-12 11:24 UTC, logan-anderson commented
@Enigmatical Thanks for the feedback I have updated based on your comments.

2021-05-12 14:24 UTC, Enigmatical approved these changes

2021-05-12 15:45 UTC, merged